version: "3"

tasks:
  deps:
    desc: Install project dependencies
    cmds:
      - cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %

  env:
    desc: Follow prompts to generate a new .env file for local development
    cmds:
      - |
        printf "CloudFlare Account ID: "
        stty -echo
        read account
        export account=$account
        stty echo

        printf "\n"

        printf "CloudFlare API Token: "
        stty -echo
        read token
        export token=$token
        stty echo

        printf "\n"

        printf "Network ID: "
        stty -echo
        read network
        export network=$network
        stty echo

        envsubst '$account,$token,$network' < .env.template > .env

        sed 's/"//g' .env > .env.docker

        unset token
        unset account
    silent: true
    preconditions:
      - sh: test ! -f .env
        msg: .env already exists. Refusing to overwrite.
      - sh: which envsubst
        msg: Must have `envsubst` installed to run this task

  run:once:
    desc: Run qrkdns once
    vars:
      DOTENV:
        sh: cat .env | grep -v "#" | xargs
    cmds:
      - "{{.DOTENV}} go run cmds/qrkdns/main.go sync"
    silent: true

  run:cron:
    desc: Run qrkdns on a cron
    vars:
      DOTENV:
        sh: cat .env | grep -v "#" | xargs
    cmds:
      - "{{.DOTENV}} go run cmds/qrkdns/main.go sync cron"
    silent: true

  test:
    desc: Run package tests
    cmds:
      - task: test-base
      - >
        cat coverage.out
        | grep -v
        -e "mocks/"
        -e "cmds/"
        > coverage.out.tmp
      - mv coverage.out.tmp coverage.out
      - task: coverage

  test-base:
    desc: Run package tests
    cmds:
      - go clean -testcache
      - go test -mod=vendor -coverpkg=./... -coverprofile=coverage.out ./...

  test-cover:
    desc: Run all tests and display coverage report
    deps:
      - test-base
    cmds:
      - go tool cover -html=coverage.out

  coverage:
    desc: Exits in non-zero if total coverage is below threshold
    vars:
      THRESHOLD: 100
    cmds:
      - >
        coverage=$(go tool cover -func=coverage.out | grep "total:" | grep -o -E '1?[0-9][0-9]?.[0-9]');
        echo "Total Coverage:" $coverage%;
        if awk "BEGIN {exit !($coverage < {{.THRESHOLD}})}"; then
          echo "[FAIL] Total coverage is less than {{.THRESHOLD}}%"
          exit 1
        else
          echo [PASS]
          exit 0
        fi
    preconditions:
      - test -f coverage.out
    silent: true

  lint:
    desc: Lint code
    cmds:
      - golangci-lint run --config .golangci.yml --verbose
    preconditions:
      - which golangci-lint

  docker:login:
    desc: Login to ghcr.io
    cmds:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
    preconditions:
      - sh: test ! -z "$GITHUB_USERNAME"
        msg: Must set the GITHUB_USERNAME environment variable
      - sh: test ! -z "$GITHUB_TOKEN"
        msg: Must set the GITHUB_TOKEN environment variable

  docker:build:local:
    desc: Build the docker image locally
    cmds:
      - docker build --pull --rm -f ./Dockerfile -t qrkdns:latest "."

  docker:run:local:
    desc: Run the application locally with provided .env.docker variables
    deps:
      - docker:build:local
    cmds:
      - docker run --env-file .env.docker --rm -it  qrkdns:latest sync

  docker:run:remote:
    desc: Run the application from the latest build with provided .env.docker variables
    deps:
      - docker:login
    cmds:
      - docker run --pull always --rm --env-file .env.docker ghcr.io/markliederbach/qrkdns:latest sync

  goreleaser:check:
    desc: Validate the Goreleaser configuration
    cmds:
      - ${GOPATH}/bin/goreleaser check
    preconditions:
      - sh: ${GOPATH}/bin/goreleaser --version
        msg: Run `task deps` to install Go tools

  goreleaser:build:
    desc: Build a snapshot locally
    cmds:
      - ${GOPATH}/bin/goreleaser build --snapshot --rm-dist
    preconditions:
      - sh: ${GOPATH}/bin/goreleaser --version
        msg: Run `task deps` to install Go tools

  goreleaser:run:once:
    desc: Run the local binary produced from goreleaser
    vars:
      DOTENV:
        sh: cat .env | grep -v "#" | xargs
    deps:
      - goreleaser:build
    cmds:
      - "{{.DOTENV}} ./dist/qrkdns_darwin_amd64/qrkdns sync"

  bump:
    vars:
      CHANGE_TYPE: '{{default "nil" .CHANGE_TYPE}}'
      CURRENT_TAG:
        sh: git describe --tags | grep -o -E \\d+\\.\\d+\\.\\d+
    cmds:
      - |
        level="{{.CHANGE_TYPE}}"
        tag="{{.CURRENT_TAG}}"
        current="${tag//v}"
        major=$(echo $current | cut -d. -f1)
        minor=$(echo $current | cut -d. -f2)
        patch=$(echo $current | cut -d. -f3)
        case $level in
            patch)
                patch=$((patch+1))
            ;;
            minor)
                patch=0
                minor=$((minor+1))
            ;;
            major)
                patch=0
                minor=0
                major=$((major+1))
            ;;
            *)
                echo "Invalid level passed"
                return 2
        esac
        new="v$major.$minor.$patch"
        echo "[Current] v$current -> [New] $new"
        git tag $new && git push origin $new
    preconditions:
      - sh: "[[ $(git rev-parse --abbrev-ref HEAD) == 'main' ]]"
        msg: Must be on main to push a tag
      - sh: "git diff --quiet"
        msg: No uncommmitted files allowed before publishing
      - sh: "[ '{{.CHANGE_TYPE}}' != 'nil' ]"
        msg: Must run one of `task bump:[major, minor, patch]`
    silent: true

  bump:major:
    desc: Bump the major version
    cmds:
      - task: bump
        vars: { CHANGE_TYPE: "major" }
  bump:minor:
    desc: Bump the minor version
    cmds:
      - task: bump
        vars: { CHANGE_TYPE: "minor" }
  bump:patch:
    desc: Bump the patch version
    cmds:
      - task: bump
        vars: { CHANGE_TYPE: "patch" }
